name: aoc_2019
version: 0.0.1-dev
author: Ivan Inozemtsev <ivan.inozemtsev@gmail.com>
desciption: advent of code solutions

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  quiver: ^2.1.0

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
